#!/usr/bin/env python
import socket
import sys,os

server_name='buildserver-ub.sh.intel.com'
PORT='16180'
Ubuntu_flag=os.popen("cat /proc/version | grep Ubuntu | wc -l").read()
Red_Hat_flag=os.popen("cat /proc/version | grep 'Red Hat' | wc -l").read()

host=os.popen("ping " + server_name + \
	" -c 1 | grep PING | cut -d \( -f 2 | cut -d \) -f 1").read()

def start_tunnel(str_remoteIP, str_port):
    tmp = os.popen("ps -ef")
    tmp2 = tmp.read()
    tmp.close()
    if tmp2.find(str_port) < 0:
        os.system("ssh -Nf -L {1}:127.0.0.1:{1} autotestexclusiveuser@{0}".format(str_remoteIP, str_port))
        os.system("sleep 2")


if int(Ubuntu_flag) == 1 :
	remoteIP, str_PORT = socket.gethostbyname(host), PORT
elif int(Red_Hat_flag) == 1 :
	remoteIP, str_PORT = socket.gethostbyname(host), PORT
else:
	print "Please check your system version!"

data = " ".join(sys.argv[1:])

start_tunnel(remoteIP, str_PORT)
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

try:
    sock.connect(('127.0.0.1', int(str_PORT)))
    sock.sendall( str(sys.argv[1:])  )
    received = sock.recv(1<<20)
finally:
    sock.close

print "Sent:\n%s" % (data)
print "Received:\n%s" % (received)
exec received
